
DB_NAME = 'Data'
TOKEN_LIST_URI = f"https://raw.githubusercontent.com/tokimay/Full_Access_Wallet/main/resources/tokenList.json"
ETH_ICON_URI = f"https://raw.githubusercontent.com/tokimay/Full_Access_Wallet/main/resources/tokensLogo/ETH.png"
GUI_ITEM_HEIGHT = 25
GUI_MENU_HEIGHT = 16
ICON_SIZE = 16
SEPOLIA_PROVIDER = "https://rpc-sepolia.rockx.com/"
ETHEREUM_PROVIDER = "https://rpc.ankr.com/eth"  # " "https://nodes.mewapi.io/rpc/eth"
ETHERSCAN_URI = "https://etherscan.io/"
ETH_SCAN_PRE = "https://etherscan.io/address/"
SEPOLIA_SCAN_PRE = "https://sepolia.etherscan.io/address/"
ETHEREUM_NOD_URI = "https://ethereumnodes.com/"
SEPOLIA_NOD_URI = "https://sepolia.dev/"
MAIN_WINDOW_WIDTH = 800
MAIN_WINDOW_HEIGHT = 600
SIDE_TAB_WIDTH = 25
SIDE_TAB_MARGIN = 2
TABLE_ACCOUNT = 'accounts'
TABLE_TOKEN = 'tokens'
